### ISSUE TITLE
Pictos textures look weird

### ISSUE THREAD

**Issue by LeoLerg** [lurkook/kuro#6]
Pictos have desaturated pixels

![image](https://user-images.githubusercontent.com/89277176/208984022-8e9b6783-2703-4a76-ac3d-9381bb264e20.png)

**Comment by lurkook** [comment]
You can share with input images? I need it for debugging purposes.

**Comment by LeoLerg** [comment]
![bodyroll_ar](https://user-images.githubusercontent.com/89277176/208986544-4e30e727-42ae-489c-aa19-7a7b7fb675d8.png)

**Comment by lurkook** [comment]
Thanks. I will research about this issue tomorrow.
*P.s. I will post updates as new comments!*

**Comment by lurkook** [comment]
*UPD.* This was compression problem. I added re-masking functionality which can be useful in situations like this.

### Example
![example](https://user-images.githubusercontent.com/117036757/209106231-e3078cd0-f018-4ba7-a6e1-f0d4c4c6ea48.png)

First was made without ``--white-alpha`` parameter.
Second was made with ``--white-alpha`` parameter.

**Comment by lurkook** [comment]
**Warning!** I don't recommend to using it for everything. *Because of this, i made this function optional...*
